name: Download and Upload Crossword Puzzle

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 8 * * *' # Scheduled to run every day at 2 AM

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install xword-dl
          pip install pydrive  # Installing library for Google Drive access

      - name: Download Puzzle
        run: |
          DATE=$(date +'%Y%m%d')
          xword-dl nd --latest -o ./puzzle_$DATE.puz

      # Setup Google Drive API credentials from GitHub secret
      - name: Setup Google Drive API Credentials
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" > credentials.json

      - name: Upload puzzle to Google Drive
        run: |
          DATE=$(date +'%Y%m%d')
          python upload_to_gdrive.py ./puzzle_$DATE.puz /Atlantic_Puzzles/puzzle_$DATE.puz
