name: Download and Upload Atlantic Crossword Puzzle

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 8 * * *' # Scheduled to run every day at 2 AM

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install xword-dl

      - name: Download Puzzle
        run: |
          DATE=$(date +'%Y%m%d')
          xword-dl nd --latest -o ./puzzle_$DATE.puz

      - name: Download Dropbox Uploader
        run: |
          curl -LO https://github.com/andreafabrizi/Dropbox-Uploader/raw/master/dropbox_uploader.sh
          chmod +x dropbox_uploader.sh

      # Create .dropbox_uploader file from GitHub secret
      - name: Setup Dropbox Uploader
        run: |
          echo "${{ secrets.DROPBOX_UPLOADER_CONFIG }}" > ~/.dropbox_uploader

      - name: Upload puzzle to Dropbox and Check Response
        run: |
          DATE=$(date +'%Y%m%d')
          echo "Before script execution"
          ./dropbox_uploader.sh -d upload ./puzzle_$DATE.puz /Atlantic_Puzzles/puzzle_$DATE.puz > /tmp/du_resp_out 2> /tmp/du_resp_err
          echo "After script execution"
          echo "Exit Status: $?"
          echo "Output File Details:"
          ls -l /tmp/du_resp_out /tmp/du_resp_err
          echo "Output Content:"
          cat /tmp/du_resp_out
          echo "Error Content:"
          cat /tmp/du_resp_err






