name: Download and Upload Crossword Puzzle

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 8 * * *' # Scheduled to run every day at 2 AM

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install xword-dl

      - name: Download Puzzle
        run: |
          DATE=$(date +'%Y%m%d')
          xword-dl nd --latest -o ./puzzle_$DATE.puz

      - name: Download Dropbox Uploader
        run: |
          curl -LO https://github.com/andreafabrizi/Dropbox-Uploader/raw/master/dropbox_uploader.sh
          chmod +x dropbox_uploader.sh

      # Assuming you have checked in the .dropbox_uploader file in your repository
      - name: Setup Dropbox Uploader
        run: |
          cp .dropbox_uploader ~/.dropbox_uploader

      - name: Upload puzzle to Dropbox
        run: |
          DATE=$(date +'%Y%m%d')
          ./dropbox_uploader.sh -f ~/.dropbox_uploader upload ./puzzle_$DATE.puz /Atlantic_Puzzles/puzzle_$DATE.puz