name: Download + Upload Atlantic Crossword Puzzle

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 13 * * *' # Scheduled to run every day at 1pm UTC or 8am 

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install xword-dl

      - name: Download Puzzle
        run: |
          DATE=$(date +'%Y%m%d_%A') 
          xword-dl nd --latest -o ./atlanticpuzzle_$DATE.puz

      - name: Upload puzzle to Dropbox
        run: |
          DATE=$(date +'%Y%m%d_%A')
          access_token=$(curl -X POST https://api.dropboxapi.com/oauth2/token \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=refresh_token" \
          --data-urlencode "refresh_token=$DROPBOX_REFRESH_TOKEN" \
          --data-urlencode "client_id=$DROPBOX_APP_KEY" \
          --data-urlencode "client_secret=$DROPBOX_APP_SECRET" | jq -r '.access_token')
          python upload_to_dropbox.py "./atlanticpuzzle_$DATE.puz" "/Atlantic_Puzzles/atlanticpuzzle_$DATE.puz" "${access_token}"
