name: Download + Upload Various Crossword Puzzles

on:
  push:
    branches:
      - main  # or your default branch name
  schedule:
    - cron: '0 13 * * *' # Scheduled to run every day at 1pm UTC or 8am 

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Install Dependencies
        run: |
          pip install xword-dl

      - name: Download Puzzle
        continue-on-error: true
        run: |
          DATE=$(date +'%Y%m%d_%A') 
          xword-dl nd --latest -o ./newsday_$DATE.puz
          xword-dl atl --latest -o ./atlanticpuzzle_$DATE.puz
          xword-dl db --latest -o ./dailybeastpuzzle_$DATE.puz
          xword-dl std --latest -o ./derstandardpuzzle_$DATE.puz
          xword-dl lat --latest -o ./losangelestimespuzzle_$DATE.puz
          xword-dl mck --latest -o ./themckinleypuzzle_$DATE.puz
          xword-dl uni --latest -o ./universalpuzzle_$DATE.puz
          xword-dl usa --latest -o ./usatodaypuzzle_$DATE.puz
          xword-dl vox --latest -o ./voxpuzzle_$DATE.puz

      - name: Upload puzzle to Dropbox
        run: |
          DATE=$(date +'%Y%m%d_%A')
          response=$(curl https://api.dropbox.com/oauth2/token \
            -d grant_type=refresh_token \
            -d refresh_token=${{ secrets.REFRESH_TOKEN }} \
            --data-urlencode "client_id=${{ secrets.APP_KEY }}" \
            --data-urlencode "client_secret=${{ secrets.APP_SECRET }}")
          access_token=$(echo $response | jq -r '.access_token')
          echo "NEW_DROPBOX_ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

          declare -A puzzles
          puzzles[newsday]="Newsday_Puzzles"
          puzzles[atlanticpuzzle]="Atlantic_Puzzles"
          puzzles[dailybeastpuzzle]="Dailybeast_Puzzles"
          puzzles[derstandardpuzzle]="Derstandard_Puzzles"
          puzzles[losangelestimespuzzle]="LATimes_Puzzles"
          puzzles[themckinleypuzzle]="Themckinley_Puzzles"
          puzzles[universalpuzzle]="Universal_Puzzles"
          puzzles[usatodaypuzzle]="USAToday_Puzzles"
          puzzles[voxpuzzle]="Vox_Puzzles"

          for puzzle in "${!puzzles[@]}"; do
            file="./${puzzle}_$DATE.puz"
            if [[ -f $file ]]; then
              python upload_to_dropbox.py "$file" "/${puzzles[$puzzle]}/${puzzle}_$DATE.puz" "$access_token"
            else
              echo "File $file does not exist, skipping upload."
            fi
          done